#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook "alm",
  :path => "../alm-cookbook"
cookbook "ruby",
  :git => "git@github.com:articlemetrics/ruby-cookbook.git"
cookbook "passenger_nginx",
  :git => "git@github.com:articlemetrics/passenger_nginx-cookbook.git"
cookbook "capistrano",
  :git => "git@github.com:articlemetrics/capistrano-cookbook.git"
cookbook "mysql", '~> 5.4.3'
cookbook 'database', '~> 2.3.0'
cookbook "phantomjs"
cookbook "memcached"
cookbook "couchdb"
cookbook "postfix"
